### ISSUE TITLE
the air conditioner does not start

### ISSUE THREAD

**Issue by balbulator** [marts2007/zanussi#1]
installed files in HA, registered the configuration, but I do not know how to control the air conditioner (ZACS/I-09 HV).
Object created "climate.konditsioner"
hvac_modes:
  - 'off'
  - cool
  - heat
min_temp: 16
max_temp: 32
target_temp_step: 1
fan_modes:
  - auto
  - low
  - mid
  - turbo
current_temperature: 27.4
temperature: 16
fan_mode: auto
last_on_operation: cool
device_code: 0
manufacturer: ZANUSSI
supported_models:
  - ZACS/I-09 HV/A18/N1
friendly_name: Кондиционер
supported_features: 9

But the automation of turning on by the Aqara button does not work, nor does the air conditioner start by manually starting the automation. 
Can you help?

**Comment by marts2007** [comment]
Try to add "thermostat" card to your HA dashboard and check if it works.
